# platform: linux/amd64 ◀ DBで使うとエラー回避できるかも
version: '3.9'
services:
  strapi:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: strapi
    command: npm run develop
    # environment:
    #   - NODE_ENV=production
    ports:
      - 1337:1337
    volumes:
      - .:/srv/app
    stdin_open: true
    tty: true
  db:
    image: postgres
    environment:
      - POSTGRES_DB=strapi
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    container_name: strapi-db
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
